//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carnotaurus.GhostPubsMvc.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookItem
    {
        public int BookItemId { get; set; }
        public int BookId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public string TradingName { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string AlternativeTown { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Org Org { get; set; }
    }
}
