//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carnotaurus.GhostPubsMvc.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentPage
    {
        public int PageID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> PageTemplateID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Lead { get; set; }
        public string WellHeader { get; set; }
        public string Description { get; set; }
        public string HtmlText { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
