//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carnotaurus.GhostPubsMvc.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureType
    {
        public FeatureType()
        {
            this.Features = new HashSet<Feature>();
        }
    
        public int FeatureTypeID { get; set; }
        public Nullable<int> ParentFeatureTypeID { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual ICollection<Feature> Features { get; set; }
    }
}
